# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AaaWI9nCuWJlh50BL5vRSWCUEH4p1vyc
"""

import pandas as pd

df = pd.read_csv('/content/sample_data/Salary.csv')

import pandas as pd
df = pd.read_csv('/content/sample_data/Salary.csv')

for column in df.columns:
    if df[column].isnull().any():
        if pd.api.types.is_numeric_dtype(df[column]):
            df[column].fillna(df[column].mean(), inplace=True)
        else:
            # For non-numeric columns, fill with the mode. If there are multiple modes, take the first one.
            df[column].fillna(df[column].mode()[0], inplace=True)

print("Null values after imputation:")
print(df.isnull().sum())

duplicate_rows = df[df.duplicated()]

print(f"Number of duplicate rows: {len(duplicate_rows)}")

if not duplicate_rows.empty:
    print("Duplicate rows:")
    display(duplicate_rows)

from sklearn.model_selection import train_test_split

# Assuming 'Salary' is the target variable
# Adjust 'Salary' if your target column has a different name
X = df.drop('Salary', axis=1)  # Features
y = df['Salary']              # Target

# Split the data into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

from sklearn.linear_model import LinearRegression

# Initialize the Linear Regression model
model = LinearRegression()

# Train the model using the training data
model.fit(X_train, y_train)

print("Linear Regression Model Trained Successfully!")
print(f"Coefficients: {model.coef_}")
print(f"Intercept: {model.intercept_}")

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print(f"Mean Absolute Error (MAE): {mae:.2f}")
print(f"Mean Squared Error (MSE): {mse:.2f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.2f}")
print(f"R-squared (R2): {r2:.2f}")

from sklearn.tree import DecisionTreeRegressor

# Initialize the Decision Tree Regressor model
dt_model = DecisionTreeRegressor(random_state=42)

# Train the model
dt_model.fit(X_train, y_train)

print("Decision Tree Regressor Model Trained Successfully!")

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Make predictions on the test set using the Decision Tree model
dt_y_pred = dt_model.predict(X_test)

# Evaluate the Decision Tree model
dt_mae = mean_absolute_error(y_test, dt_y_pred)
dt_mse = mean_squared_error(y_test, dt_y_pred)
dt_rmse = np.sqrt(dt_mse)
dt_r2 = r2_score(y_test, dt_y_pred)

print("\nDecision Tree Regressor Model Evaluation:")
print(f"Mean Absolute Error (MAE): {dt_mae:.2f}")
print(f"Mean Squared Error (MSE): {dt_mse:.2f}")
print(f"Root Mean Squared Error (RMSE): {dt_rmse:.2f}")
print(f"R-squared (R2): {dt_r2:.2f}")

import pickle

# Save the best model (Decision Tree Regressor) to a .pkl file
filename = 'best_model.pkl'
pickle.dump(dt_model, open(filename, 'wb'))

print(f"Best model saved to {filename}")

"""The `best_model.pkl` file has been created. You can now download it from the Colab environment if needed, or load it in a future session using `loaded_model = pickle.load(open('best_model.pkl', 'rb'))`."""

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))
sns.scatterplot(x='YearsExperience', y='Salary', data=df)
plt.title('Scatter Plot of Salary vs YearsExperience')
plt.xlabel('Years of Experience')
plt.ylabel('Salary')
plt.grid(True)
plt.show()

display(df.head())